### ISSUE TITLE
Database migration fails to set up database

### ISSUE THREAD

**Issue by takluyver** [pygame/pygameweb#10]
I tried to follow the instructions to set up the database and run the web server locally for testing, but the database migration step (`alembic upgrade head`) failed like this:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 47683b299022, Initial db, before import of old db.
INFO  [alembic.runtime.migration] Running upgrade 47683b299022 -> c4e6d5863a94, Removing unused tables. Adding tag index.
Traceback (most recent call last):
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: index "public_tags_project_id0_idx" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/takluyver/miniconda3/envs/pygameweb/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/takluyver/Websites/pygameweb/pygameweb/alembic/env.py", line 82, in <module>
    run_migrations_online()
  File "/home/takluyver/Websites/pygameweb/pygameweb/alembic/env.py", line 77, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/takluyver/Websites/pygameweb/pygameweb/alembic/versions/c4e6d5863a94_removing_unused_tables_adding_tag_index.py", line 24, in upgrade
    op.drop_index('public_tags_project_id0_idx', table_name='tags')
  File "<string>", line 8, in drop_index
  File "<string>", line 3, in drop_index
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/operations/ops.py", line 964, in drop_index
    return operations.invoke(op)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 94, in drop_index
    operation.to_index(operations.migration_context)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/ddl/impl.py", line 209, in drop_index
    self._exec(schema.DropIndex(index))
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/takluyver/miniconda3/envs/pygameweb/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) index "public_tags_project_id0_idx" does not exist
 [SQL: '\nDROP INDEX public_tags_project_id0_idx']
```

And then accessing the web server fails with a database error, presumably because it hasn't been set up correctly.

**Comment by takluyver** [comment]
I worked around this by, uh, commenting out the failing commands in the migration scripts, and re-running until it succeeded.

**Comment by poikilos** [comment]
If anyone is interested, I documented the exact steps necessary when testing another issue (see attachments at the following): https://github.com/pygame/pygameweb/issues/62
